---
title: "List of supported variables"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{List of supported variables}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Intoduction
This vignette gives a complete list of all variables that are supported by the different *set* functions. To see how to specify these variables inside the *set* functions, see [Preparing your data for plotting](set_data.html).

## List
<style>
td {
  font-size: 100%
}</style>

### Soil variables
Treating data on soil variables can be challenging since any varibale can have more than one value per observation. This occurs whenever data on a variable is given individually for each layer of the soil. The function `set_soil` distinguishes between variables that are povided by soil and those that are provided by soil and layer---the latter ones bear the prefix `layer_`. See the vignette  [Preparing your data for plotting](set_data.html) for more information.

|Variable|Definition|Calculation done if not present|
|---|---|---|
|`id`| Unique soil identification|*essential function argument*|
|`depth`| Soil depth, total|sum over all layers of `layer_depth`|
|`layer_depth`| Soil depth, by layer||
|`saturated_wtr_cap`| Soil saturated water capacity, total|sum over all layers of `layer_saturated_wtr_cap`|
|`layer_saturated_wtr_cap`| Soil saturated water capacity, by layer|`layer_depth` * `layer_bulk_density_moist` * ( `layer_water_field_cap` - `layer_water_wilting_pt` ) * `units::set_units(0.1, "mm cm2 g-1", mode = "standard")`|
|`organic_N_conc`| Soil organic nitrogen concentration, total||
|`layer_water_field_cap`| Soil water field capacity, by layer||
|`layer_water_wilting_pt`| Soil water wilting point, by layer||
|`layer_bulk_density_moist`| Soil bulk density when moist, per layer||



### Weather variables
Weather variables have to be given to `set_weather` in a single data frame for each observation. Hence, all variables have to be given for each day.

|Variable|Definition|Calculation done if not present|
|---|---|---|
|`id`| Unique weather identification||
|`station_name`| Weather station name||
|`temp_day_max`| Air temperature, daily maximum||
|`temp_day_min`| Air temperature, daily minimum||
|`temp_day_mean`| Air temperature, daily mean|`(temp_day_max + temp_day_min) / 2`|
|`rainfall_day`| Rainfall, per day||
|`year`|year of observation||
